export const SignupDepartments = [
  "IT",
  "MECH",
  "CS&E",
  "AIDS",
  "AIML",
  "COMP",
  "E&IC",
  "ES&H",
  "CIVIL",
  "IOT",
  "MME",
  "E&CS",
  "BVOC",
  "MISC",
];

export const role_and_departments = {
  PRINCIPAL: ["PRINCIPAL"],
  VICE_PRINCIPAL: ["VICE_PRINCIPAL"],
  DEAN: ["SSW", "R&D", "ACADEMICS", "TPO"],
  ASSOCIATE_DEAN: [
    "QAC",
    "Planning&Operation",
    "Skill Development and Vocational Subjects",
    "Administration & Compliance",
  ],
  HOD: [
    "IT",
    "MECH",
    "CS&E",
    "AIDS",
    "AIML",
    "COMP",
    "E&IC",
    "ES&H",
    "CIVIL",
    "IOT",
    "MME",
    "E&CS",
    "BVOC",
  ],
  EXAM_SECTION: ["EXAM_SECTION"],
  T_N_P: ["T_N_P"],
  CLERKS: ["CLERKS"],
  R_N_D: ["R_N_D"],
  H_O_C: ["H_O_C"],
  LIBRARIAN: ["LIBRARIAN"],
  HOSTEL: ["HOSTEL"],
  ACCOUNTS: ["ACCOUNTS"],
  ADMIN: ["ADMIN"],
  FACULTY: [
    "IT",
    "MECH",
    "CS&E",
    "AIDS",
    "AIML",
    "COMP",
    "E&IC",
    "ES&H",
    "CIVIL",
    "IOT",
    "MME",
    "E&CS",
    "BVOC",
  ],
  ICT: ["ICT"],
};

export const turn_in_receivers = [
  "PRINCIPAL",
  "VICE_PRINCIPAL",
  "DEAN SSW",
  "DEAN R&D",
  "DEAN ACADEMICS",
  "DEAN TPO",
  "ASSOCIATE_DEAN QAC",
  "ASSOCIATE_DEAN Planning&Operation",
  "ASSOCIATE_DEAN Skill Development and Vocational Subjects",
  "ASSOCIATE_DEAN Administration & Compliance",
  "HOD IT",
  "HOD MECH",
  "HOD CS&E",
  "HOD AIDS",
  "HOD AIML",
  "HOD COMP",
  "HOD E&IC",
  "HOD ES&H",
  "HOD CIVIL",
  "HOD IOT",
  "HOD MME",
  "HOD E&CS",
  "HOD BVOC",

  "Faculty IT",
  "Faculty MECH",
  "Faculty CS&E",
  "Faculty AIDS",
  "Faculty AIML",
  "Faculty COMP",
  "Faculty E&IC",
  "Faculty ES&H",
  "Faculty CIVIL",
  "Faculty IOT",
  "Faculty MME",
  "Faculty E&CS",
  "Faculty BVOC",
  "EXAM_SECTION",
  "T_N_P",
  "R_N_D",
  "H_O_C",
  "LIBRARIAN",
  "HOSTEL",
  "ACCOUNTS",
  "ADMIN",
  "ICT",
];
